import Navbar from "@/components/Navbar";
import React from "react";
import Footer from "@/components/Footer";
import Tab from "@/components/guide/Tab";

export const metadata = {
  title: "Battle Grid - Guide",
  description: "Generated by create next app",
};

const Guide = () => {
  return (
    <main>
      <Navbar />
      <div className="hidden md:hidden lg:block">
        <Tab />
      </div>
    </main>
  );
};

export default Guide;
